import type { Post, Notification } from '@/types'

export const communityPosts: Post[] = [
  {
    id: 'p1',
    creatorId: 'apdhillon',
    authorName: 'RajveerSingh',
    authorAvatar: 'RS',
    authorIsVerified: false,
    content: "AP just dropped a teaser on IG. New collab incoming 🔥 this is why I bought at $0.85. Sitting on 3x right now and not selling anytime soon.",
    likes: 342,
    comments: 48,
    shares: 22,
    isLiked: true,
    timestamp: '2026-06-14T08:30:00Z',
    sentiment: 'bullish',
  },
  {
    id: 'p2',
    creatorId: 'apdhillon',
    authorName: 'MusicInvestor99',
    authorAvatar: 'MI',
    authorIsVerified: false,
    content: "Just did the math on AP's Spotify streams + tour dates. Revenue pool should distribute nicely next quarter. This is undervalued at $2.45 imo.",
    likes: 218,
    comments: 31,
    shares: 14,
    isLiked: false,
    timestamp: '2026-06-14T06:15:00Z',
    sentiment: 'bullish',
  },
  {
    id: 'p3',
    creatorId: 'pesopluma',
    authorName: 'LatinWaveInvestor',
    authorAvatar: 'LW',
    authorIsVerified: false,
    content: "Peso Pluma just dropped a teaser for a collab with Bad Bunny. Latin wave is unstoppable. Still early at $3.75.",
    likes: 892,
    comments: 134,
    shares: 67,
    isLiked: false,
    timestamp: '2026-06-13T21:45:00Z',
    sentiment: 'bullish',
  },
  {
    id: 'p4',
    creatorId: 'sza',
    authorName: 'RnBEarlySpotter',
    authorAvatar: 'RE',
    authorIsVerified: false,
    content: "SZA's SOS era is still running strong 18 months later. New music incoming. This is a long hold for me.",
    likes: 1204,
    comments: 287,
    shares: 156,
    isLiked: true,
    timestamp: '2026-06-14T10:00:00Z',
    sentiment: 'bullish',
  },
  {
    id: 'p5',
    creatorId: 'burnaboy',
    authorName: 'AfrobeatsBull',
    authorAvatar: 'AB',
    authorIsVerified: false,
    content: "Burna Boy just announced a world tour. Afrobeats going global — this is the wave. Spotted $BURNA early and not looking back.",
    likes: 445,
    comments: 92,
    shares: 31,
    isLiked: false,
    timestamp: '2026-06-14T09:12:00Z',
    sentiment: 'bullish',
  },
  {
    id: 'p6',
    creatorId: 'flume',
    authorName: 'ElectronicHead',
    authorAvatar: 'EH',
    authorIsVerified: false,
    content: "Flume's new album has been in rotation for 3 months. The festival lineup confirms he's back. $FLUME is criminally undervalued.",
    likes: 567,
    comments: 74,
    shares: 38,
    isLiked: false,
    timestamp: '2026-06-13T18:30:00Z',
    sentiment: 'bullish',
  },
  {
    id: 'p7',
    creatorId: 'lilnasx',
    authorName: 'LongTermHold',
    authorAvatar: 'LH',
    authorIsVerified: true,
    content: "Lil Nas X new album announcement sent streams up 340%. World tour selling fast. The cultural conversation is back at full volume. 10x thesis intact.",
    likes: 2341,
    comments: 445,
    shares: 312,
    isLiked: true,
    timestamp: '2026-06-12T14:20:00Z',
    sentiment: 'bullish',
  },
]

export const notifications: Notification[] = [
  {
    id: 'n1',
    type: 'price_up',
    title: 'PESOPLUMA is up 12.8%',
    message: 'Peso Pluma shares surged on Bad Bunny collab announcement.',
    ticker: 'PESOPLUMA',
    isRead: false,
    timestamp: '2026-06-14T10:00:00Z',
  },
  {
    id: 'n2',
    type: 'creator_update',
    title: 'AP Dhillon posted an update',
    message: 'New single dropping this Friday. Pre-save now 🔥',
    ticker: 'APDHILLON',
    isRead: false,
    timestamp: '2026-06-14T08:00:00Z',
  },
  {
    id: 'n3',
    type: 'new_ipo',
    title: 'Emma Chamberlain IPO closes in 6 days',
    message: '$EMMA is 82% funded. Only $138k left until close.',
    ticker: 'EMMA',
    isRead: false,
    timestamp: '2026-06-14T07:30:00Z',
  },
  {
    id: 'n4',
    type: 'trade_executed',
    title: 'Buy order filled',
    message: '200 shares of LILNASX purchased at $3.20/share',
    ticker: 'LILNASX',
    isRead: true,
    timestamp: '2026-06-13T14:32:00Z',
  },
  {
    id: 'n5',
    type: 'price_up',
    title: 'APDHILLON is up 12.3%',
    message: 'AP Dhillon shares spiked on new tour announcement.',
    ticker: 'APDHILLON',
    isRead: true,
    timestamp: '2026-06-13T09:15:00Z',
  },
]
