import type { Post, Notification } from '@/types'

export const communityPosts: Post[] = [
  {
    id: 'p1',
    creatorId: 'apdhillon',
    authorName: 'RajveerSingh',
    authorAvatar: 'RS',
    authorIsVerified: false,
    content: "AP just dropped a teaser on IG. New collab incoming 🔥 this is why I bought at $0.85. Sitting on 3x right now and not selling anytime soon.",
    likes: 342,
    comments: 48,
    shares: 22,
    isLiked: true,
    timestamp: '2026-06-14T08:30:00Z',
    sentiment: 'bullish',
  },
  {
    id: 'p2',
    creatorId: 'apdhillon',
    authorName: 'MusicInvestor99',
    authorAvatar: 'MI',
    authorIsVerified: false,
    content: "Just did the math on AP's Spotify streams + tour dates. Revenue pool should distribute nicely next quarter. This is undervalued at $2.45 imo.",
    likes: 218,
    comments: 31,
    shares: 14,
    isLiked: false,
    timestamp: '2026-06-14T06:15:00Z',
    sentiment: 'bullish',
  },
  {
    id: 'p3',
    creatorId: 'mrbeast',
    authorName: 'DeepakTrades',
    authorAvatar: 'DT',
    authorIsVerified: false,
    content: "MrBeast just announced a new Africa video series partnering with 5 governments. This thing is going to $15 EOY. Adding more shares at $8.90.",
    likes: 892,
    comments: 134,
    shares: 67,
    isLiked: false,
    timestamp: '2026-06-13T21:45:00Z',
    sentiment: 'bullish',
  },
  {
    id: 'p4',
    creatorId: 'ishowspeed',
    authorName: 'HypeMaximalist',
    authorAvatar: 'HM',
    authorIsVerified: false,
    content: "+45% in one day. Speed met Ronaldo AGAIN. I called this at $0.42. If he drops a collab with Messi this thing goes parabolic 🚀",
    likes: 1204,
    comments: 287,
    shares: 156,
    isLiked: true,
    timestamp: '2026-06-14T10:00:00Z',
    sentiment: 'bullish',
  },
  {
    id: 'p5',
    creatorId: 'ishowspeed',
    authorName: 'CautionZone',
    authorAvatar: 'CZ',
    authorIsVerified: false,
    content: "Taking some profits at $1.80. These pumps are volatile. Already sold 30% of my position. Not financial advice, just managing risk.",
    likes: 445,
    comments: 92,
    shares: 31,
    isLiked: false,
    timestamp: '2026-06-14T09:12:00Z',
    sentiment: 'bearish',
  },
  {
    id: 'p6',
    creatorId: 'kaicenat',
    authorName: 'TwitchWatcher',
    authorAvatar: 'TW',
    authorIsVerified: false,
    content: "Kai's last subathon brought in 300k subs. Next one is rumored for July. Stock will moon. This dip to $3.20 is a gift fr.",
    likes: 567,
    comments: 74,
    shares: 38,
    isLiked: false,
    timestamp: '2026-06-13T18:30:00Z',
    sentiment: 'bullish',
  },
  {
    id: 'p7',
    creatorId: 'mrbeast',
    authorName: 'LongTermHold',
    authorAvatar: 'LH',
    authorIsVerified: true,
    content: "Feastables is now in 35 countries. YouTube AdSense alone is estimated at $54M/year. The fundamentals on $MRBEAST are insane. 10x from here.",
    likes: 2341,
    comments: 445,
    shares: 312,
    isLiked: true,
    timestamp: '2026-06-12T14:20:00Z',
    sentiment: 'bullish',
  },
]

export const notifications: Notification[] = [
  {
    id: 'n1',
    type: 'price_up',
    title: 'SPEED is up 45.2%',
    message: 'IShowSpeed shares surged after viral Ronaldo meet-up video.',
    ticker: 'SPEED',
    isRead: false,
    timestamp: '2026-06-14T10:00:00Z',
  },
  {
    id: 'n2',
    type: 'creator_update',
    title: 'AP Dhillon posted an update',
    message: 'New single dropping this Friday. Pre-save now 🔥',
    ticker: 'APDHILLON',
    isRead: false,
    timestamp: '2026-06-14T08:00:00Z',
  },
  {
    id: 'n3',
    type: 'new_ipo',
    title: 'Emma Chamberlain IPO closes in 6 days',
    message: '$EMMA is 82% funded. Only $138k left until close.',
    ticker: 'EMMA',
    isRead: false,
    timestamp: '2026-06-14T07:30:00Z',
  },
  {
    id: 'n4',
    type: 'trade_executed',
    title: 'Buy order filled',
    message: '500 shares of SPEED purchased at $1.23/share',
    ticker: 'SPEED',
    isRead: true,
    timestamp: '2026-06-13T14:32:00Z',
  },
  {
    id: 'n5',
    type: 'price_up',
    title: 'APDHILLON is up 12.3%',
    message: 'AP Dhillon shares spiked on new tour announcement.',
    ticker: 'APDHILLON',
    isRead: true,
    timestamp: '2026-06-13T09:15:00Z',
  },
]
