import type { Creator, PricePoint } from '@/types'

function generatePriceHistory(
  basePrice: number,
  days: number,
  trend: 'up' | 'down' | 'volatile' | 'parabolic',
  endPrice: number
): PricePoint[] {
  const points: PricePoint[] = []
  const start = new Date('2025-09-15')
  let price = basePrice

  for (let i = 0; i < days; i++) {
    const date = new Date(start)
    date.setDate(start.getDate() + i)
    const progress = i / (days - 1)
    const target = basePrice + (endPrice - basePrice) * progress

    let noise = 0
    if (trend === 'volatile') noise = (Math.sin(i * 0.8) * basePrice * 0.06) + (Math.cos(i * 1.3) * basePrice * 0.03)
    else if (trend === 'parabolic') noise = Math.pow(progress, 2) * basePrice * 0.2 + (Math.sin(i * 0.5) * basePrice * 0.02)
    else if (trend === 'up') noise = Math.sin(i * 0.4) * basePrice * 0.04
    else noise = Math.cos(i * 0.5) * basePrice * 0.03

    price = Math.max(0.01, target + noise)

    points.push({
      date: date.toISOString().split('T')[0],
      price: parseFloat(price.toFixed(3)),
    })
  }

  return points
}

export const creators: Creator[] = [
  {
    id: 'apdhillon',
    ticker: 'APDHILLON',
    name: 'AP Dhillon',
    category: 'Music',
    bio: 'Punjabi-Canadian sensation blending R&B and Punjabi pop. Toured globally, 10M+ monthly Spotify listeners, collaborations with Intense and Gurinder Gill.',
    avatar: 'AD',
    coverColor: 'from-purple-600 to-pink-600',
    status: 'active',
    price: 2.45,
    priceChange24h: 0.27,
    priceChangePercent24h: 12.35,
    marketCap: 2450000,
    volume24h: 184200,
    totalShares: 1000000,
    floatShares: 200000,
    sharesHeld: 120000,
    followers: '14.2M',
    creatorScore: 84,
    socialHandles: {
      instagram: '@apdhillon',
      spotify: 'AP Dhillon',
      youtube: 'AP Dhillon Official',
    },
    revenueMetrics: {
      monthlyListeners: '10.2M',
      streams: '2.1B',
    },
    priceHistory: generatePriceHistory(0.85, 90, 'up', 2.45),
    isVerified: true,
    isWatched: true,
    imageUrl: 'https://i.scdn.co/image/ab6761610000e5ebfb505b37709fa86cfd8f55b3',
    story: 'North American tour sold out in 48 hours. Punjabi-Canadian icon breaking worldwide streaming records.',
    catalysts: [
      { label: 'World Tour Kickoff', date: 'Aug 2026', type: 'tour', impact: 'high' },
      { label: 'New Album Release', date: 'Jul 2026', type: 'album', impact: 'high' },
      { label: 'Coachella Headliner', date: 'Oct 2026', type: 'appearance', impact: 'medium' },
    ],
  },
  {
    id: 'lilnasx',
    ticker: 'LILNASX',
    name: 'Lil Nas X',
    category: 'Music',
    bio: 'Grammy winner. Old Town Road broke Billboard records. Cultural icon blending country, hip-hop, and pop with fearless authenticity.',
    avatar: 'LN',
    coverColor: 'from-yellow-400 to-orange-500',
    status: 'active',
    price: 4.50,
    priceChange24h: 0.36,
    priceChangePercent24h: 8.70,
    marketCap: 4500000,
    volume24h: 213000,
    totalShares: 1000000,
    floatShares: 200000,
    sharesHeld: 142000,
    followers: '28M',
    creatorScore: 86,
    socialHandles: {
      instagram: '@lilnasx',
      spotify: 'Lil Nas X',
      youtube: 'Lil Nas X',
    },
    revenueMetrics: {
      monthlyListeners: '18.5M',
      streams: '8.2B',
    },
    priceHistory: generatePriceHistory(2.80, 90, 'up', 4.50),
    isVerified: true,
    isWatched: true,
    imageUrl: 'https://i.scdn.co/image/ab6761610000e5eb3758a33e782b46bd7f174e1d',
    story: 'Grammy winner. New album announcement sent streams up 340%. World tour selling fast.',
    catalysts: [
      { label: 'New Album Drop', date: 'Jul 2026', type: 'album', impact: 'high' },
      { label: 'World Tour Launch', date: 'Oct 2026', type: 'tour', impact: 'high' },
      { label: 'Versace Collab', date: 'Aug 2026', type: 'collab', impact: 'medium' },
    ],
  },
  {
    id: 'corpse',
    ticker: 'CORPSE',
    name: 'CORPSE Husband',
    category: 'Music',
    bio: 'Faceless mystery creator. Deep voice became a cultural phenomenon. Horror storytelling turned musician. Among Us era breakout star.',
    avatar: 'CH',
    coverColor: 'from-gray-800 to-black',
    status: 'active',
    price: 1.20,
    priceChange24h: 0.22,
    priceChangePercent24h: 22.47,
    marketCap: 1200000,
    volume24h: 412000,
    totalShares: 1000000,
    floatShares: 200000,
    sharesHeld: 76000,
    followers: '18M',
    creatorScore: 74,
    socialHandles: {
      youtube: 'CORPSE Husband',
      spotify: 'CORPSE',
    },
    revenueMetrics: {
      monthlyListeners: '3.2M',
    },
    priceHistory: generatePriceHistory(0.50, 90, 'parabolic', 1.20),
    isVerified: true,
    isWatched: false,
    imageUrl: 'https://i.scdn.co/image/ab6761610000e5ebed2fd5aa8e1c20922c190d30',
    story: 'New single crossed 5M plays in 24 hours. Mystery persona driving record community engagement.',
  },

  // ── New creators ──────────────────────────────────────────────────────────────

  {
    id: 'shubh',
    ticker: 'SHUBH',
    name: 'Shubh',
    category: 'Music',
    bio: 'Punjabi trap pioneer. From SoundCloud to sold-out arenas. Blending desi rhythms with global production.',
    avatar: 'SH',
    coverColor: 'from-orange-600 to-amber-700',
    status: 'active',
    price: 1.65,
    priceChange24h: 0.21,
    priceChangePercent24h: 14.6,
    marketCap: 1650000,
    volume24h: 210000,
    totalShares: 1000000,
    floatShares: 200000,
    sharesHeld: 88000,
    followers: '8.4M',
    creatorScore: 79,
    socialHandles: { instagram: '@shubh', spotify: 'Shubh', youtube: 'Shubh' },
    revenueMetrics: { monthlyListeners: '3.8M', streams: '800M' },
    priceHistory: generatePriceHistory(0.60, 90, 'up', 1.65),
    isVerified: true,
    isWatched: false,
    imageUrl: 'https://i.scdn.co/image/ab6761610000e5eb9dfbd284ba8a7d4876a181e3',
    story: 'UK tour sold out in 6 hours. Trending in 6 countries simultaneously. Collab with AP Dhillon incoming.',
    catalysts: [
      { label: 'Europe Arena Tour', date: 'Sep 2026', type: 'tour', impact: 'high' },
      { label: 'New Album Drop', date: 'Aug 2026', type: 'album', impact: 'high' },
    ],
  },
  {
    id: 'karanaujla',
    ticker: 'KARANAUJLA',
    name: 'Karan Aujla',
    category: 'Music',
    bio: 'Punjabi-Canadian rapper-singer-songwriter with 1.2B+ lifetime streams. Bridging desi rap and Western hip-hop.',
    avatar: 'KA',
    coverColor: 'from-yellow-500 to-orange-600',
    status: 'active',
    price: 1.40,
    priceChange24h: 0.14,
    priceChangePercent24h: 11.1,
    marketCap: 1400000,
    volume24h: 168000,
    totalShares: 1000000,
    floatShares: 200000,
    sharesHeld: 74000,
    followers: '11.2M',
    creatorScore: 76,
    socialHandles: { instagram: '@karanaujla_', spotify: 'Karan Aujla', youtube: 'Karan Aujla' },
    revenueMetrics: { monthlyListeners: '5.2M', streams: '1.2B' },
    priceHistory: generatePriceHistory(0.70, 90, 'up', 1.40),
    isVerified: true,
    isWatched: false,
    imageUrl: 'https://i.scdn.co/image/ab6761610000e5eb8a4c60d0eebe893f72e42979',
    story: 'IYKYK album pre-saves breaking records. Canada arena tour dates selling out within minutes.',
    catalysts: [
      { label: 'Album "IYKYK" Release', date: 'Jul 2026', type: 'album', impact: 'high' },
      { label: 'Canada Arena Tour', date: 'Oct 2026', type: 'tour', impact: 'high' },
    ],
  },
  {
    id: 'hanumankind',
    ticker: 'HANUMANKIND',
    name: 'Hanumankind',
    category: 'Music',
    bio: 'India\'s next global rap export. Blends Malayalam, Hindi, and English over trap and drill beats. SXSW breakout.',
    avatar: 'HK',
    coverColor: 'from-red-600 to-rose-800',
    status: 'active',
    price: 0.95,
    priceChange24h: 0.19,
    priceChangePercent24h: 25.0,
    marketCap: 950000,
    volume24h: 340000,
    totalShares: 1000000,
    floatShares: 200000,
    sharesHeld: 51000,
    followers: '2.1M',
    creatorScore: 72,
    socialHandles: { instagram: '@hanumankind', spotify: 'Hanumankind', youtube: 'Hanumankind' },
    revenueMetrics: { monthlyListeners: '1.4M', streams: '180M' },
    priceHistory: generatePriceHistory(0.22, 90, 'parabolic', 0.95),
    isVerified: true,
    isWatched: false,
    imageUrl: 'https://i.scdn.co/image/ab6761610000e5ebd5a94f1d05a422f1057b0e90',
    story: 'Big Dawgs went viral in 18M plays in 72 hours. Featured on Rolling Stone India. SXSW 2026 confirmed.',
    catalysts: [
      { label: 'SXSW 2026 Showcase', date: 'Mar 2026', type: 'appearance', impact: 'high' },
      { label: 'Debut Album', date: 'Aug 2026', type: 'album', impact: 'high' },
    ],
  },
  {
    id: 'dojacat',
    ticker: 'DOJACAT',
    name: 'Doja Cat',
    category: 'Music',
    bio: 'Grammy winner. Shape-shifting pop icon. Went from SoundCloud rapper to multi-platinum hitmaker rewriting pop rules.',
    avatar: 'DC',
    coverColor: 'from-purple-500 to-fuchsia-700',
    status: 'active',
    price: 5.20,
    priceChange24h: 0.28,
    priceChangePercent24h: 5.7,
    marketCap: 5200000,
    volume24h: 312000,
    totalShares: 1000000,
    floatShares: 200000,
    sharesHeld: 189000,
    followers: '78M',
    creatorScore: 91,
    socialHandles: { instagram: '@dojacat', spotify: 'Doja Cat', tiktok: '@dojacat' },
    revenueMetrics: { monthlyListeners: '62M', streams: '12B' },
    priceHistory: generatePriceHistory(3.10, 90, 'up', 5.20),
    isVerified: true,
    isWatched: false,
    imageUrl: 'https://i.scdn.co/image/ab6761610000e5eb8a0644455ebfa7d3976f5101',
    story: 'New era rollout sending fans into overdrive. Grammy nominations across 3 categories. Coachella confirmed.',
    catalysts: [
      { label: 'New Album Era', date: 'Jul 2026', type: 'album', impact: 'high' },
      { label: 'Coachella Headliner', date: 'Apr 2026', type: 'appearance', impact: 'high' },
      { label: 'Grammy Ceremony', date: 'Feb 2026', type: 'appearance', impact: 'medium' },
    ],
  },
  {
    id: 'icespice',
    ticker: 'ICESPICE',
    name: 'Ice Spice',
    category: 'Music',
    bio: 'Bronx drill princess turned global pop force. From "Munch" to Taylor Swift collaborator. NY in her veins.',
    avatar: 'IS',
    coverColor: 'from-orange-400 to-red-500',
    status: 'active',
    price: 2.10,
    priceChange24h: 0.32,
    priceChangePercent24h: 18.0,
    marketCap: 2100000,
    volume24h: 445000,
    totalShares: 1000000,
    floatShares: 200000,
    sharesHeld: 112000,
    followers: '19M',
    creatorScore: 81,
    socialHandles: { instagram: '@icespice', tiktok: '@icespice', spotify: 'Ice Spice' },
    revenueMetrics: { monthlyListeners: '22M', streams: '3.8B' },
    priceHistory: generatePriceHistory(0.55, 90, 'parabolic', 2.10),
    isVerified: true,
    isWatched: false,
    imageUrl: 'https://i.scdn.co/image/ab6761610000e5ebab47bb63dae13065213602cd',
    story: 'Taylor Swift feature confirmed for new album. MTV VMAs performance viewed 40M times. NY is hers.',
    catalysts: [
      { label: 'Taylor Swift Collab Drop', date: 'Aug 2026', type: 'collab', impact: 'high' },
      { label: 'MTV VMAs', date: 'Sep 2026', type: 'appearance', impact: 'high' },
      { label: 'Debut Album', date: 'Oct 2026', type: 'album', impact: 'high' },
    ],
  },
  {
    id: 'sabrina',
    ticker: 'SABRINA',
    name: 'Sabrina Carpenter',
    category: 'Music',
    bio: 'Short n\' Sweet became a cultural phenomenon. From Disney to pop domination. Every song is a hit. 71M monthly listeners.',
    avatar: 'SC',
    coverColor: 'from-yellow-300 to-pink-400',
    status: 'active',
    price: 6.80,
    priceChange24h: 0.51,
    priceChangePercent24h: 8.1,
    marketCap: 6800000,
    volume24h: 520000,
    totalShares: 1000000,
    floatShares: 200000,
    sharesHeld: 231000,
    followers: '52M',
    creatorScore: 94,
    socialHandles: { instagram: '@sabrinacarpenter', spotify: 'Sabrina Carpenter', tiktok: '@sabrinacarpenter' },
    revenueMetrics: { monthlyListeners: '71M', streams: '14B' },
    priceHistory: generatePriceHistory(2.40, 90, 'up', 6.80),
    isVerified: true,
    isWatched: false,
    imageUrl: 'https://i.scdn.co/image/ab6761610000e5eb78e45cfa4697ce3c437cb455',
    story: 'Short n\' Sweet era became cultural omnipresence. Vogue cover. 71M monthly listeners and accelerating.',
    catalysts: [
      { label: 'World Tour Leg 2', date: 'Jul 2026', type: 'tour', impact: 'high' },
      { label: 'New Single Drop', date: 'Jun 2026', type: 'content', impact: 'medium' },
    ],
  },
  {
    id: 'tylertc',
    ticker: 'TYLERTC',
    name: 'Tyler the Creator',
    category: 'Music',
    bio: 'Grammy-winning polymath. Golf Wang founder. Chromakopia changed rap. Director, designer, auteur. Simply iconic.',
    avatar: 'TT',
    coverColor: 'from-green-400 to-teal-600',
    status: 'active',
    price: 4.75,
    priceChange24h: 0.15,
    priceChangePercent24h: 3.3,
    marketCap: 4750000,
    volume24h: 198000,
    totalShares: 1000000,
    floatShares: 200000,
    sharesHeld: 167000,
    followers: '22M',
    creatorScore: 93,
    socialHandles: { instagram: '@feliciathegoat', spotify: 'Tyler, the Creator', youtube: 'Tyler The Creator' },
    revenueMetrics: { monthlyListeners: '29M', streams: '10B' },
    priceHistory: generatePriceHistory(2.80, 90, 'up', 4.75),
    isVerified: true,
    isWatched: false,
    imageUrl: 'https://i.scdn.co/image/ab6761610000e5ebdf2728294ff77dd11eeb18fb',
    story: 'Chromakopia tour sold out in 8 minutes. Golf Wang collaboration with Louis Vuitton. Metacritic 97.',
    catalysts: [
      { label: 'Golf Wang × LV Drop', date: 'Jul 2026', type: 'collab', impact: 'high' },
      { label: 'Chromakopia Tour Leg 3', date: 'Sep 2026', type: 'tour', impact: 'high' },
    ],
  },
  {
    id: 'pesopluma',
    ticker: 'PESOPLUMA',
    name: 'Peso Pluma',
    category: 'Music',
    bio: 'Regional Mexican meets global pop. Billboard Hot 100 #1. Coachella headliner. Rewriting what Latin music can be.',
    avatar: 'PP',
    coverColor: 'from-red-500 to-yellow-500',
    status: 'active',
    price: 5.60,
    priceChange24h: 0.62,
    priceChangePercent24h: 12.4,
    marketCap: 5600000,
    volume24h: 487000,
    totalShares: 1000000,
    floatShares: 200000,
    sharesHeld: 214000,
    followers: '34M',
    creatorScore: 90,
    socialHandles: { instagram: '@pesopluma', spotify: 'Peso Pluma', tiktok: '@pesopluma' },
    revenueMetrics: { monthlyListeners: '54M', streams: '7.2B' },
    priceHistory: generatePriceHistory(1.20, 90, 'parabolic', 5.60),
    isVerified: true,
    isWatched: false,
    imageUrl: 'https://i.scdn.co/image/ab6761610000e5ebe5283f5b671cf618b82a2696',
    story: 'Billboard Hot 100 number one. Grammy nominated. Coachella headliner. 1.8B streams this year.',
    catalysts: [
      { label: 'World Arena Tour', date: 'Aug 2026', type: 'tour', impact: 'high' },
      { label: 'Grammy Performance', date: 'Feb 2026', type: 'appearance', impact: 'high' },
      { label: 'New Album "Éxodo"', date: 'Sep 2026', type: 'album', impact: 'high' },
    ],
  },
  {
    id: 'newjeans',
    ticker: 'NEWJEANS',
    name: 'NewJeans',
    category: 'Music',
    bio: 'K-pop\'s most innovative act. Y2K aesthetics, addictive hooks, and a global fanbase that keeps doubling. Bunny era.',
    avatar: 'NJ',
    coverColor: 'from-sky-400 to-blue-500',
    status: 'active',
    price: 4.10,
    priceChange24h: 0.48,
    priceChangePercent24h: 13.2,
    marketCap: 4100000,
    volume24h: 398000,
    totalShares: 1000000,
    floatShares: 200000,
    sharesHeld: 196000,
    followers: '41M',
    creatorScore: 89,
    socialHandles: { instagram: '@newjeans_official', spotify: 'NewJeans', tiktok: '@newjeans_official' },
    revenueMetrics: { monthlyListeners: '28M', streams: '5.4B' },
    priceHistory: generatePriceHistory(1.40, 90, 'up', 4.10),
    isVerified: true,
    isWatched: false,
    imageUrl: 'https://i.scdn.co/image/ab6761610000e5eb8dae71b664393f38ba91f891',
    story: 'Japan debut sold out in 2 minutes. Levi\'s collaboration going global. 28M Spotify monthly listeners.',
    catalysts: [
      { label: 'World Tour Announcement', date: 'Jul 2026', type: 'tour', impact: 'high' },
      { label: 'Levi\'s × NewJeans Drop', date: 'Jun 2026', type: 'collab', impact: 'high' },
      { label: 'New EP Release', date: 'Aug 2026', type: 'album', impact: 'medium' },
    ],
  },

  // ── Latin ─────────────────────────────────────────────────────────────────

  {
    id: 'badbunny',
    ticker: 'BUNNY',
    name: 'Bad Bunny',
    category: 'Music',
    bio: 'Puerto Rican superstar redefining Latin music worldwide. Three-time most-streamed artist on Spotify globally. Merges reggaeton, trap, cumbia, and rock.',
    avatar: 'BB',
    coverColor: 'from-yellow-500 to-green-600',
    status: 'active',
    price: 6.82,
    priceChange24h: 0.45,
    priceChangePercent24h: 7.06,
    marketCap: 6820000,
    volume24h: 612000,
    totalShares: 1000000,
    floatShares: 200000,
    sharesHeld: 198000,
    followers: '52.3M',
    creatorScore: 96,
    socialHandles: { instagram: '@badbunnypr', spotify: 'Bad Bunny', youtube: 'Bad Bunny' },
    revenueMetrics: { monthlyListeners: '42M', streams: '9.8B', concertRevenue: '$6.1M/yr', merch: '$1.2M/yr' },
    priceHistory: generatePriceHistory(4.20, 90, 'up', 6.82),
    isVerified: true,
    imageUrl: 'https://i.scdn.co/image/ab6761610000e5eb81f47f44084e0a09b5f0fa13',
    story: 'Most-streamed artist on Spotify 3 years running. Un Verano Sin Ti broke all-time Latin streaming records.',
    catalysts: [
      { label: 'New Album Cycle Confirmed', date: '2026-08', type: 'album', impact: 'high' },
      { label: 'World Tour — Americas + Europe', date: '2026-09', type: 'tour', impact: 'high' },
    ],
  },
  {
    id: 'karolg',
    ticker: 'KAROLG',
    name: 'Karol G',
    category: 'Music',
    bio: 'Colombian reggaeton queen with global crossover appeal. Mañana Será Bonito broke Spotify records for female Latin artists. Bichota forever.',
    avatar: 'KG',
    coverColor: 'from-teal-400 to-blue-600',
    status: 'active',
    price: 4.15,
    priceChange24h: 0.32,
    priceChangePercent24h: 8.35,
    marketCap: 4150000,
    volume24h: 395000,
    totalShares: 1000000,
    floatShares: 200000,
    sharesHeld: 190000,
    followers: '28.1M',
    creatorScore: 89,
    socialHandles: { instagram: '@karolg', spotify: 'Karol G', tiktok: '@karolg' },
    revenueMetrics: { monthlyListeners: '30M', streams: '6.2B', concertRevenue: '$3.8M/yr', merch: '$880K/yr' },
    priceHistory: generatePriceHistory(2.10, 90, 'up', 4.15),
    isVerified: true,
    imageUrl: 'https://i.scdn.co/image/ab6761610000e5eb66041ce9eb4497057cbc3496',
    story: 'Mañana Será Bonito made history as first Spanish-language female album to top Billboard 200.',
    catalysts: [
      { label: 'Mañana Será Bonito Tour — Final Leg', date: '2026-07', type: 'tour', impact: 'high' },
      { label: 'New Single Release', date: '2026-06', type: 'album', impact: 'medium' },
    ],
  },
  {
    id: 'jbalvin',
    ticker: 'BALVIN',
    name: 'J Balvin',
    category: 'Music',
    bio: 'Colombian reggaeton pioneer and global Latin ambassador. Collaborations with Beyoncé, Bad Bunny, Cardi B, and Skrillex. 22M+ monthly listeners.',
    avatar: 'JB',
    coverColor: 'from-purple-500 to-pink-600',
    status: 'active',
    price: 3.28,
    priceChange24h: 0.18,
    priceChangePercent24h: 5.81,
    marketCap: 3280000,
    volume24h: 298000,
    totalShares: 1000000,
    floatShares: 200000,
    sharesHeld: 185000,
    followers: '22.4M',
    creatorScore: 82,
    socialHandles: { instagram: '@jbalvin', spotify: 'J Balvin', youtube: 'J Balvin' },
    revenueMetrics: { monthlyListeners: '22M', streams: '4.8B', concertRevenue: '$2.9M/yr', merch: '$620K/yr' },
    priceHistory: generatePriceHistory(2.40, 90, 'volatile', 3.28),
    isVerified: true,
    imageUrl: 'https://i.scdn.co/image/ab6761610000e5eb0405b03342c2e56751b9923d',
    story: 'El Alfa collab breaking Latin trap records. New Skrillex co-produced EP incoming.',
  },
  {
    id: 'ozuna',
    ticker: 'OZUNA',
    name: 'Ozuna',
    category: 'Music',
    bio: 'Puerto Rican reggaeton and Latin trap superstar. Known as "El Negrito de Ojos Claros." Consistent chart dominance since 2016 with 25M+ followers.',
    avatar: 'OZ',
    coverColor: 'from-blue-600 to-indigo-700',
    status: 'active',
    price: 2.95,
    priceChange24h: -0.08,
    priceChangePercent24h: -2.64,
    marketCap: 2950000,
    volume24h: 245000,
    totalShares: 1000000,
    floatShares: 200000,
    sharesHeld: 180000,
    followers: '25.8M',
    creatorScore: 78,
    socialHandles: { instagram: '@ozuna', spotify: 'Ozuna', youtube: 'Ozunapr' },
    revenueMetrics: { monthlyListeners: '18M', streams: '3.9B', concertRevenue: '$2.2M/yr', merch: '$480K/yr' },
    priceHistory: generatePriceHistory(2.80, 90, 'volatile', 2.95),
    isVerified: true,
    imageUrl: 'https://i.scdn.co/image/ab6761610000e5eb1c4284179078e2529b1630e2',
  },

  // ── K-Pop ─────────────────────────────────────────────────────────────────

  {
    id: 'blackpink',
    ticker: 'BPINK',
    name: 'BLACKPINK',
    category: 'Music',
    bio: 'South Korean global K-pop phenomenon. The most-followed music group on Spotify. Each member is a solo brand force. BLINK fandom sets streaming records regularly.',
    avatar: 'BP',
    coverColor: 'from-pink-500 to-rose-700',
    status: 'active',
    price: 5.45,
    priceChange24h: 0.62,
    priceChangePercent24h: 12.84,
    marketCap: 5450000,
    volume24h: 528000,
    totalShares: 1000000,
    floatShares: 200000,
    sharesHeld: 196000,
    followers: '44.7M',
    creatorScore: 92,
    socialHandles: { instagram: '@blackpinkofficial', spotify: 'BLACKPINK', youtube: 'BLACKPINK', tiktok: '@blackpink' },
    revenueMetrics: { monthlyListeners: '35M', streams: '7.2B', concertRevenue: '$5.4M/yr', merch: '$1.8M/yr' },
    priceHistory: generatePriceHistory(2.80, 90, 'up', 5.45),
    isVerified: true,
    imageUrl: 'https://i.scdn.co/image/ab6761610000e5eb623538b7014238c54ceee056',
    story: 'Born Pink world tour became highest-grossing K-pop concert run ever. Members solo album cycles all charting globally.',
    catalysts: [
      { label: 'Group Comeback Announced', date: '2026-09', type: 'album', impact: 'high' },
      { label: 'YG × Valentino Campaign', date: '2026-07', type: 'collab', impact: 'medium' },
    ],
  },
  {
    id: 'straykids',
    ticker: 'SKIDS',
    name: 'Stray Kids',
    category: 'Music',
    bio: 'South Korean self-produced K-pop group. Write and produce their own music. Solo act momentum accelerating globally. STAYs are one of the most devoted K-pop fandoms.',
    avatar: 'SK',
    coverColor: 'from-slate-700 to-zinc-900',
    status: 'active',
    price: 3.72,
    priceChange24h: 0.41,
    priceChangePercent24h: 12.38,
    marketCap: 3720000,
    volume24h: 358000,
    totalShares: 1000000,
    floatShares: 200000,
    sharesHeld: 190000,
    followers: '14.2M',
    creatorScore: 85,
    socialHandles: { instagram: '@realstraykids', spotify: 'Stray Kids', youtube: 'Stray Kids', tiktok: '@officialsbs' },
    revenueMetrics: { monthlyListeners: '14M', streams: '3.1B', concertRevenue: '$3.2M/yr', merch: '$980K/yr' },
    priceHistory: generatePriceHistory(1.90, 90, 'up', 3.72),
    isVerified: true,
    imageUrl: 'https://i.scdn.co/image/ab6761610000e5ebf9887d2c9288f0e50a3fd69f',
    story: 'ATE album debuted at #1 on Billboard 200. MANIAC viral moment brought new global listeners.',
    catalysts: [
      { label: 'Dominic Toretto World Tour', date: '2026-08', type: 'tour', impact: 'high' },
      { label: 'New Mini-Album', date: '2026-07', type: 'album', impact: 'medium' },
    ],
  },
  {
    id: 'aespa',
    ticker: 'AESPA',
    name: 'aespa',
    category: 'Music',
    bio: 'SM Entertainment K-pop group blending AI concept with mainstream pop. Viral "Next Level" put them on the global radar. MYs fandom growing fast.',
    avatar: 'AE',
    coverColor: 'from-violet-500 to-purple-700',
    status: 'active',
    price: 2.85,
    priceChange24h: 0.28,
    priceChangePercent24h: 10.94,
    marketCap: 2850000,
    volume24h: 265000,
    totalShares: 1000000,
    floatShares: 200000,
    sharesHeld: 182000,
    followers: '9.8M',
    creatorScore: 80,
    socialHandles: { instagram: '@aespa_official', spotify: 'aespa', youtube: 'aespa', tiktok: '@aespa_official' },
    revenueMetrics: { monthlyListeners: '10M', streams: '2.2B', concertRevenue: '$2.1M/yr', merch: '$720K/yr' },
    priceHistory: generatePriceHistory(1.50, 90, 'up', 2.85),
    isVerified: true,
    imageUrl: 'https://i.scdn.co/image/ab6761610000e5eb053bbb910dda6d4ab0618b8b',
    story: 'Armageddon mini-album hitting #1 in 12 countries. Coachella performance went globally viral.',
  },
  {
    id: 'bts',
    ticker: 'BTS',
    name: 'BTS',
    category: 'Music',
    bio: 'South Korean group that broke every K-pop record. Currently on individual hiatus with solo projects. Group return highly anticipated by 100M+ ARMY fandom.',
    avatar: 'BT',
    coverColor: 'from-purple-600 to-indigo-700',
    status: 'active',
    price: 8.20,
    priceChange24h: -0.15,
    priceChangePercent24h: -1.80,
    marketCap: 8200000,
    volume24h: 695000,
    totalShares: 1000000,
    floatShares: 200000,
    sharesHeld: 199000,
    followers: '47.1M',
    creatorScore: 94,
    socialHandles: { instagram: '@bts.bighitofficial', spotify: 'BTS', youtube: 'BANGTANTV', twitter: '@BTS_twt' },
    revenueMetrics: { monthlyListeners: '38M', streams: '8.4B', concertRevenue: '$7.2M/yr', merch: '$2.4M/yr' },
    priceHistory: generatePriceHistory(7.00, 90, 'volatile', 8.20),
    isVerified: true,
    imageUrl: 'https://i.scdn.co/image/ab6761610000e5ebf80ec63ea7a0ef0fba60957d',
    story: 'Group return from military service confirmed. Solo projects each charting globally. Comeback is the most anticipated K-pop event of 2026.',
    catalysts: [
      { label: 'Group Reunion Comeback', date: '2026-09', type: 'album', impact: 'high' },
      { label: 'BTS Festa 2026 Event', date: '2026-06', type: 'appearance', impact: 'medium' },
    ],
  },

  // ── Afrobeats ─────────────────────────────────────────────────────────────

  {
    id: 'burnaboy',
    ticker: 'BURNA',
    name: 'Burna Boy',
    category: 'Music',
    bio: 'Nigerian Afrobeats superstar and Grammy winner. African Giant pioneer bringing Afrobeats to worldwide arenas. Love Damini confirmed his crossover dominance.',
    avatar: 'BB',
    coverColor: 'from-yellow-600 to-orange-600',
    status: 'active',
    price: 3.85,
    priceChange24h: 0.44,
    priceChangePercent24h: 12.93,
    marketCap: 3850000,
    volume24h: 362000,
    totalShares: 1000000,
    floatShares: 200000,
    sharesHeld: 190000,
    followers: '15.3M',
    creatorScore: 88,
    socialHandles: { instagram: '@burnaboygram', spotify: 'Burna Boy', youtube: 'Burna Boy' },
    revenueMetrics: { monthlyListeners: '16M', streams: '3.4B', concertRevenue: '$3.2M/yr', merch: '$680K/yr' },
    priceHistory: generatePriceHistory(2.10, 90, 'up', 3.85),
    isVerified: true,
    imageUrl: 'https://i.scdn.co/image/ab6761610000e5ebb4e44d0f4e3e47af2cf06f3f',
    story: 'I Told Them album debuted top 3 on Billboard 200. Sold out 02 Arena London — a first for an Afrobeats act.',
    catalysts: [
      { label: 'New Album Release', date: '2026-07', type: 'album', impact: 'high' },
      { label: 'Global Arena Tour', date: '2026-09', type: 'tour', impact: 'high' },
    ],
  },
  {
    id: 'wizkid',
    ticker: 'WIZKID',
    name: 'Wizkid',
    category: 'Music',
    bio: 'Nigerian Afropop legend. "Essence" remix with Justin Bieber cemented his global crossover. Afrobeats ambassador who opened the genre to mainstream audiences.',
    avatar: 'WK',
    coverColor: 'from-green-600 to-emerald-700',
    status: 'active',
    price: 2.65,
    priceChange24h: 0.19,
    priceChangePercent24h: 7.74,
    marketCap: 2650000,
    volume24h: 228000,
    totalShares: 1000000,
    floatShares: 200000,
    sharesHeld: 182000,
    followers: '11.2M',
    creatorScore: 79,
    socialHandles: { instagram: '@wizkidayo', spotify: 'Wizkid', youtube: 'Wizkid' },
    revenueMetrics: { monthlyListeners: '12M', streams: '2.6B', concertRevenue: '$2.4M/yr', merch: '$520K/yr' },
    priceHistory: generatePriceHistory(1.85, 90, 'up', 2.65),
    isVerified: true,
    imageUrl: 'https://i.scdn.co/image/ab6761610000e5ebe6ef803356b45ee5a9fa7a8a',
    story: 'More Love Less Ego shows genre maturity. "Bad to Me" collab with Brent Faiyaz charting in 40+ countries.',
  },
  {
    id: 'tems',
    ticker: 'TEMS',
    name: 'Tems',
    category: 'Music',
    bio: 'Nigerian alt-R&B and Afrobeats artist with a voice that stops rooms. Collaborated with Drake, Beyoncé, Future. Rising fast into global arena headliner territory.',
    avatar: 'TM',
    coverColor: 'from-rose-500 to-pink-700',
    status: 'active',
    price: 2.40,
    priceChange24h: 0.35,
    priceChangePercent24h: 17.07,
    marketCap: 2400000,
    volume24h: 215000,
    totalShares: 1000000,
    floatShares: 200000,
    sharesHeld: 176000,
    followers: '7.4M',
    creatorScore: 76,
    socialHandles: { instagram: '@temsbaby', spotify: 'Tems', youtube: 'Tems' },
    revenueMetrics: { monthlyListeners: '8M', streams: '1.8B', concertRevenue: '$1.8M/yr', merch: '$380K/yr' },
    priceHistory: generatePriceHistory(1.20, 90, 'parabolic', 2.40),
    isVerified: true,
    imageUrl: 'https://i.scdn.co/image/ab6761610000e5eb22d7d6f8981c7a27bf68a382',
    story: 'Grammy winner. "Free Mind" streamed by Beyoncé live. Born in the Wild album shows full artistic range.',
    catalysts: [
      { label: 'Headline World Tour', date: '2026-08', type: 'tour', impact: 'high' },
    ],
  },
  {
    id: 'davido',
    ticker: 'DAVIDO',
    name: 'Davido',
    category: 'Music',
    bio: 'Nigerian Afrobeats pioneer with 13M+ followers. Known for highlife-influenced sound and massive Pan-African fanbase. Timeless is his most critically acclaimed work.',
    avatar: 'DV',
    coverColor: 'from-orange-500 to-red-600',
    status: 'active',
    price: 2.20,
    priceChange24h: 0.08,
    priceChangePercent24h: 3.77,
    marketCap: 2200000,
    volume24h: 182000,
    totalShares: 1000000,
    floatShares: 200000,
    sharesHeld: 172000,
    followers: '13.8M',
    creatorScore: 72,
    socialHandles: { instagram: '@davido', spotify: 'Davido', youtube: 'Davido' },
    revenueMetrics: { monthlyListeners: '9M', streams: '2.0B', concertRevenue: '$2.0M/yr', merch: '$420K/yr' },
    priceHistory: generatePriceHistory(1.90, 90, 'volatile', 2.20),
    isVerified: true,
    imageUrl: 'https://i.scdn.co/image/ab6761610000e5eb057fdb13352beee124b79051',
  },

  // ── R&B & Soul ────────────────────────────────────────────────────────────

  {
    id: 'sza',
    ticker: 'SZA',
    name: 'SZA',
    category: 'Music',
    bio: 'TDE R&B artist redefining neo-soul for Gen Z. SOS broke streaming records and dominated year-end charts. Grammy winner building one of music\'s most passionate fanbases.',
    avatar: 'SZ',
    coverColor: 'from-indigo-500 to-violet-700',
    status: 'active',
    price: 4.25,
    priceChange24h: 0.58,
    priceChangePercent24h: 15.82,
    marketCap: 4250000,
    volume24h: 412000,
    totalShares: 1000000,
    floatShares: 200000,
    sharesHeld: 194000,
    followers: '22.8M',
    creatorScore: 90,
    socialHandles: { instagram: '@sza', spotify: 'SZA', twitter: '@sza' },
    revenueMetrics: { monthlyListeners: '22M', streams: '4.9B', concertRevenue: '$3.1M/yr', merch: '$720K/yr' },
    priceHistory: generatePriceHistory(2.20, 90, 'parabolic', 4.25),
    isVerified: true,
    imageUrl: 'https://i.scdn.co/image/ab6761610000e5ebfd0a9fb6c252a3ba44079acf',
    story: 'SOS spent record 10 weeks at #1 on Billboard 200. Lana collab "Saturn" has 400M+ streams.',
    catalysts: [
      { label: 'New Album Announced', date: '2026-07', type: 'album', impact: 'high' },
      { label: 'SZA × Lana Del Rey Tour', date: '2026-08', type: 'tour', impact: 'high' },
    ],
  },
  {
    id: 'weeknd',
    ticker: 'WEEKND',
    name: 'The Weeknd',
    category: 'Music',
    bio: 'Canadian R&B and pop superstar. Most-streamed artist milestone holder. Blinding Lights became the longest-charting Hot 100 song ever. Hurry Up Tomorrow completing the trilogy.',
    avatar: 'TW',
    coverColor: 'from-red-800 to-zinc-900',
    status: 'active',
    price: 7.15,
    priceChange24h: 0.22,
    priceChangePercent24h: 3.17,
    marketCap: 7150000,
    volume24h: 580000,
    totalShares: 1000000,
    floatShares: 200000,
    sharesHeld: 199000,
    followers: '47.5M',
    creatorScore: 93,
    socialHandles: { instagram: '@theweeknd', spotify: 'The Weeknd', twitter: '@theweeknd' },
    revenueMetrics: { monthlyListeners: '45M', streams: '10.2B', concertRevenue: '$6.8M/yr', merch: '$1.9M/yr' },
    priceHistory: generatePriceHistory(5.80, 90, 'up', 7.15),
    isVerified: true,
    imageUrl: 'https://i.scdn.co/image/ab6761610000e5ebc1719ac9e6a75c1c25835018',
    story: 'Hurry Up Tomorrow film and album releasing simultaneously. The Weeknd XO era is closing with a cultural moment.',
    catalysts: [
      { label: 'Hurry Up Tomorrow Album Drop', date: '2026-06', type: 'album', impact: 'high' },
      { label: 'After Hours Til Dawn Final Tour', date: '2026-08', type: 'tour', impact: 'high' },
    ],
  },
  {
    id: 'her',
    ticker: 'HER',
    name: 'H.E.R.',
    category: 'Music',
    bio: 'Grammy and Oscar-winning R&B artist and multi-instrumentalist. Known for soulful live performances and advocacy for music\'s roots. Bridging soul, blues, and contemporary R&B.',
    avatar: 'HR',
    coverColor: 'from-amber-600 to-orange-700',
    status: 'active',
    price: 1.85,
    priceChange24h: 0.12,
    priceChangePercent24h: 6.93,
    marketCap: 1850000,
    volume24h: 148000,
    totalShares: 1000000,
    floatShares: 200000,
    sharesHeld: 168000,
    followers: '7.2M',
    creatorScore: 68,
    socialHandles: { instagram: '@hermusicofficial', spotify: 'H.E.R.', twitter: '@hermusicofficial' },
    revenueMetrics: { monthlyListeners: '6M', streams: '1.2B', concertRevenue: '$1.2M/yr', merch: '$280K/yr' },
    priceHistory: generatePriceHistory(1.40, 90, 'up', 1.85),
    isVerified: true,
    imageUrl: 'https://i.scdn.co/image/ab6761610000e5eb417db49cde3ed1c5a65e3514',
  },
  {
    id: 'giveon',
    ticker: 'GIVEON',
    name: 'Giveon',
    category: 'Music',
    bio: 'Long Beach soul singer with a baritone voice that stands apart. Collaborated with Drake, Justin Bieber. Heartbreak Anniversary went viral and launched a new soul era.',
    avatar: 'GV',
    coverColor: 'from-blue-700 to-indigo-800',
    status: 'active',
    price: 2.05,
    priceChange24h: 0.15,
    priceChangePercent24h: 7.89,
    marketCap: 2050000,
    volume24h: 168000,
    totalShares: 1000000,
    floatShares: 200000,
    sharesHeld: 172000,
    followers: '7.8M',
    creatorScore: 71,
    socialHandles: { instagram: '@giveon', spotify: 'Giveon', twitter: '@giveon' },
    revenueMetrics: { monthlyListeners: '7M', streams: '1.5B', concertRevenue: '$1.4M/yr', merch: '$320K/yr' },
    priceHistory: generatePriceHistory(1.60, 90, 'up', 2.05),
    isVerified: true,
    imageUrl: 'https://i.scdn.co/image/ab6761610000e5ebe357870455bc56f7ef4147f8',
  },

  // ── Electronic ────────────────────────────────────────────────────────────

  {
    id: 'skrillex',
    ticker: 'SKRLL',
    name: 'Skrillex',
    category: 'Music',
    bio: 'EDM pioneer and Grammy winner. Co-wrote and produced hits across hip-hop and pop. Quest For Fire and Don\'t Get Too Close marked a massive comeback and genre reinvention.',
    avatar: 'SK',
    coverColor: 'from-yellow-400 to-orange-500',
    status: 'active',
    price: 2.75,
    priceChange24h: 0.38,
    priceChangePercent24h: 16.02,
    marketCap: 2750000,
    volume24h: 245000,
    totalShares: 1000000,
    floatShares: 200000,
    sharesHeld: 182000,
    followers: '15.6M',
    creatorScore: 80,
    socialHandles: { instagram: '@skrillex', spotify: 'Skrillex', twitter: '@skrillex' },
    revenueMetrics: { monthlyListeners: '14M', streams: '3.0B', festivalRevenue: '$4.2M/yr', merch: '$580K/yr' },
    priceHistory: generatePriceHistory(1.60, 90, 'parabolic', 2.75),
    isVerified: true,
    imageUrl: 'https://i.scdn.co/image/ab6761610000e5ebf3103acde767f8daf964d5bd',
    story: 'Quest For Fire and Don\'t Get Too Close released in same year — a historic double-album moment. Festival headline season announced.',
    catalysts: [
      { label: 'Coachella 2026 Headline Set', date: '2026-04', type: 'appearance', impact: 'high' },
      { label: 'New Album Announced', date: '2026-08', type: 'album', impact: 'high' },
    ],
  },
  {
    id: 'diplo',
    ticker: 'DIPLO',
    name: 'Diplo',
    category: 'Music',
    bio: 'World-class DJ and producer. Founder of Mad Decent. Blends global sounds from cumbia to electronic. Thomas Wesley and LSD are his most critically acclaimed projects.',
    avatar: 'DP',
    coverColor: 'from-cyan-500 to-blue-600',
    status: 'active',
    price: 1.95,
    priceChange24h: 0.14,
    priceChangePercent24h: 7.74,
    marketCap: 1950000,
    volume24h: 152000,
    totalShares: 1000000,
    floatShares: 200000,
    sharesHeld: 168000,
    followers: '12.4M',
    creatorScore: 70,
    socialHandles: { instagram: '@diplo', spotify: 'Diplo', twitter: '@diplo' },
    revenueMetrics: { monthlyListeners: '10M', streams: '2.2B', festivalRevenue: '$3.8M/yr', merch: '$420K/yr' },
    priceHistory: generatePriceHistory(1.60, 90, 'volatile', 1.95),
    isVerified: true,
    imageUrl: 'https://i.scdn.co/image/ab6761610000e5ebdf01727aa674ddefa777797a',
  },
  {
    id: 'porterrobinson',
    ticker: 'PORTER',
    name: 'Porter Robinson',
    category: 'Music',
    bio: 'Electronic producer and vocalist. Nurture album became a landmark of indie dance music. Virtual Self alter-ego explores techno. Live shows are deeply immersive experiences.',
    avatar: 'PR',
    coverColor: 'from-pink-400 to-violet-500',
    status: 'active',
    price: 2.15,
    priceChange24h: 0.28,
    priceChangePercent24h: 14.97,
    marketCap: 2150000,
    volume24h: 192000,
    totalShares: 1000000,
    floatShares: 200000,
    sharesHeld: 174000,
    followers: '5.1M',
    creatorScore: 74,
    socialHandles: { instagram: '@porterrobinson', spotify: 'Porter Robinson', twitter: '@porterrobinson' },
    revenueMetrics: { monthlyListeners: '5M', streams: '1.1B', festivalRevenue: '$2.2M/yr', merch: '$380K/yr' },
    priceHistory: generatePriceHistory(1.40, 90, 'parabolic', 2.15),
    isVerified: true,
    imageUrl: 'https://i.scdn.co/image/ab6761610000e5eb1ac12dcb2cc4fc7c740c5e0c',
    story: 'Second Sky festival sold out in 4 minutes. New project in development — fans speculating full ambient album.',
    catalysts: [
      { label: 'Second Sky 2026 Festival', date: '2026-10', type: 'appearance', impact: 'high' },
    ],
  },
  {
    id: 'flume',
    ticker: 'FLUME',
    name: 'Flume',
    category: 'Music',
    bio: 'Australian producer pioneering future bass and ambient electronic. Palaces showcased mature artistic evolution. Grammy winner exploring the edge of electronic music.',
    avatar: 'FL',
    coverColor: 'from-teal-400 to-cyan-600',
    status: 'active',
    price: 1.75,
    priceChange24h: 0.10,
    priceChangePercent24h: 6.06,
    marketCap: 1750000,
    volume24h: 128000,
    totalShares: 1000000,
    floatShares: 200000,
    sharesHeld: 164000,
    followers: '5.4M',
    creatorScore: 66,
    socialHandles: { instagram: '@flumemusic', spotify: 'Flume', twitter: '@flumemusic' },
    revenueMetrics: { monthlyListeners: '5M', streams: '980M', festivalRevenue: '$1.8M/yr', merch: '$290K/yr' },
    priceHistory: generatePriceHistory(1.50, 90, 'up', 1.75),
    isVerified: false,
    imageUrl: 'https://i.scdn.co/image/ab6761610000e5ebd6ec6e1162ee709ad829cf82',
  },
]

export function getCreatorByTicker(ticker: string): Creator | undefined {
  return creators.find(c => c.ticker.toLowerCase() === ticker.toLowerCase())
}

export function getCreatorsByTickers(tickers: string[]): Creator[] {
  const upper = tickers.map(t => t.toUpperCase())
  return creators.filter(c => upper.includes(c.ticker))
}

export function getTrendingCreators(limit = 6): Creator[] {
  return [...creators]
    .sort((a, b) => Math.abs(b.priceChangePercent24h) - Math.abs(a.priceChangePercent24h))
    .slice(0, limit)
}

export function getTopGainers(limit = 5): Creator[] {
  return [...creators]
    .filter(c => c.priceChangePercent24h > 0)
    .sort((a, b) => b.priceChangePercent24h - a.priceChangePercent24h)
    .slice(0, limit)
}

export function getCreatorsByCategory(category: string): Creator[] {
  if (category === 'All') return creators
  return creators.filter(c => c.category === category)
}
