import type { IPOCreator } from '@/types'

export const ipoCreators: IPOCreator[] = [
  {
    id: 'lildurk',
    ticker: 'DURK',
    name: 'Lil Durk',
    category: 'Music',
    bio: 'Chicago drill pioneer. Multiple platinum albums, chart-topping collaborations. Raised from the streets to global hip-hop royalty.',
    avatar: 'LD',
    coverColor: 'from-amber-500 to-yellow-700',
    fundraisingGoal: 500000,
    fundingProgress: 342000,
    totalShares: 1000000,
    initialPrice: 0.10,
    launchDate: '2026-06-28',
    pitch: "I've built one of the most loyal fanbases in hip-hop. Now I'm giving my fans a real stake in my journey. Every stream, every tour, every deal — my community grows with me.",
    useOfFunds: [
      'New album production & distribution',
      'World tour logistics',
      'Merchandise line expansion',
      'Artist management team',
    ],
    revenueStreams: [
      'Streaming royalties (Spotify, Apple Music)',
      'Touring & live events',
      'Merchandise & apparel',
      'Brand sponsorships',
    ],
    followers: '32M',
    socialHandles: {
      instagram: '@lildurk',
      spotify: 'Lil Durk',
    },
    status: 'open',
    daysUntilLaunch: 14,
    imageUrl: 'https://images.unsplash.com/photo-1480455624526-1cfd63e2c8ab?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'clix',
    ticker: 'CLIX',
    name: 'Clix',
    category: 'Gaming',
    bio: "Fortnite prodigy turned content creator. Multiple tournament wins, top competitive player. Gen-Z's favorite gaming icon.",
    avatar: 'CX',
    coverColor: 'from-blue-500 to-indigo-700',
    fundraisingGoal: 250000,
    fundingProgress: 78000,
    totalShares: 1000000,
    initialPrice: 0.10,
    launchDate: '2026-07-05',
    pitch: "I've competed at the highest level and built a massive community. This raise will help me build a content empire and training facility for the next gen of competitive players.",
    useOfFunds: [
      'Professional gaming setup & facility',
      'Content production team',
      'Tournament travel & coaching',
      'Community events',
    ],
    revenueStreams: [
      'Streaming subscriptions & donations',
      'Tournament prize pools',
      'Sponsorship deals',
      'YouTube ad revenue',
    ],
    followers: '8.5M',
    socialHandles: {
      twitch: 'clix',
      youtube: 'Clix',
      instagram: '@clix',
    },
    status: 'open',
    daysUntilLaunch: 21,
    imageUrl: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'emmachamberlain',
    ticker: 'EMMA',
    name: 'Emma Chamberlain',
    category: 'Lifestyle',
    bio: 'YouTube pioneer who changed vlogging forever. Coffee entrepreneur (Chamberlain Coffee), fashion icon, and genuine Gen-Z voice.',
    avatar: 'EC',
    coverColor: 'from-rose-400 to-pink-600',
    fundraisingGoal: 750000,
    fundingProgress: 612000,
    totalShares: 1000000,
    initialPrice: 0.10,
    launchDate: '2026-06-20',
    pitch: "Chamberlain Coffee is just the beginning. I'm building a multi-channel lifestyle empire and want my most loyal fans to be part of the ride from day one.",
    useOfFunds: [
      'Chamberlain Coffee expansion',
      'Original podcast production',
      'Fashion collaborations',
      'International content creation',
    ],
    revenueStreams: [
      'Chamberlain Coffee revenue share',
      'YouTube & podcast ad revenue',
      'Brand deal fees',
      'Merchandise sales',
    ],
    followers: '22M',
    socialHandles: {
      youtube: 'Emma Chamberlain',
      instagram: '@emmachamberlain',
      tiktok: '@emmachamberlain',
    },
    status: 'open',
    daysUntilLaunch: 6,
    imageUrl: 'https://images.unsplash.com/photo-1488426862026-3ee34a7d66ef?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'newjeans',
    ticker: 'NJZ',
    name: 'NewJeans',
    category: 'Music',
    bio: "South Korea's fastest-rising K-pop group. Record-breaking debut, global fans, and a distinct Y2K aesthetic that's captivated millions.",
    avatar: 'NJ',
    coverColor: 'from-sky-400 to-blue-600',
    fundraisingGoal: 1000000,
    fundingProgress: 0,
    totalShares: 1000000,
    initialPrice: 0.10,
    launchDate: '2026-07-15',
    pitch: "NewJeans represents the next generation of global pop culture. Our Bunnies are the most dedicated fanbase in the world — and now they can truly own a piece of what we build together.",
    useOfFunds: [
      'World tour production',
      'Studio album & digital releases',
      'Global merchandise rollout',
      'Fan event infrastructure',
    ],
    revenueStreams: [
      'Music streaming royalties',
      'Concert & tour revenue',
      'Merchandise & photocards',
      'Brand endorsements',
    ],
    followers: '45M',
    socialHandles: {
      instagram: '@newjeans_official',
      youtube: 'NewJeans',
    },
    status: 'coming_soon',
    daysUntilLaunch: 31,
    imageUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=800&q=80',
  },
]
